### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by katyo** [jrburke/r.js#26]
How I can handle errors like to "Cannot find module" when I use it with node?

**Comment by zanona** [comment]
Perhaps a `onError` attribute under `config ` would also be nice ;)

**Comment by jrburke** [comment]
No plans to add an onError to the config object itself, as the config is meant to be a static representation of the build config to generate output. For the requirejs.optimize() call, there needs to be a way to communicate errors on a per-call basis, and since the process of build completion can be async, a callback passed to the call makes sense.

Going to close this as a very old bug and no more changes in this area are planned.
