### ISSUE TITLE
UTF issue when minifying some libraries like SockJS

### ISSUE THREAD

**Issue by p3k** [jrburke/r.js#585]
The version of uglify2 used in r.js seems to have some issues with some unicode characters, e.g.

```
var foo = {
  "\u200c": "bar"
};
```

becomes

```
var foo={‌:"bar"};
```

Please read the whole story at https://github.com/jrburke/requirejs/issues/962

**Comment by rejas** [comment]
Looking at https://github.com/Modernizr/Modernizr/issues/2059 right now, seems that the uglify process of v2.3.6 still optimizes our code too much :-( 

In 
https://github.com/Modernizr/Modernizr/blob/6f34ec8266a5368792eaa65b7e63a82ec955ab7e/feature-detects/es5/syntax.js#L36 
`eval('_\u200c\u200d = true');`
gets optimized to 
`eval("_ = true");`
Or is there something I am missing on our side @jrburke  ?

**Comment by jrburke** [comment]
v2.3.6 of r.js includes v2.8.29 of uglify, and I believe there are more modern, 3.x versions of uglify available. I do believe uglify 2.8.x has issues. Unfortunately I cannot embed uglifyjs 3.x since the API changed, and the bundling of uglifyjs in r.js was from a time when it was not common for people to have better node-based build processes.

Now I recommend not using the bundled uglify in r.js but using "optimize=none" for the r.js step, then run a separate command after r.js module bundling to minify with the minifier and version that you know works well for your code.
