### ISSUE TITLE
Why does r.js redefine jquery as an empty module?

### ISSUE THREAD

**Issue by philipwalton** [jrburke/r.js#718]
I was looking at the build output for my application and I noticed the following line added by r.js at the end

``` js
define("jquery", function(){});
```

jQuery already includes a define statement, so I was under the impression that r.js wouldn't need to redefine it. Here is (as I'm sure you know) what's in the jQuery source:

``` js
if ( typeof define === "function" && define.amd ) {
  define( "jquery", [], function() {
    return jQuery;
  });
}
```

---

To reproduce this, all you have to do is use the following main.js file:

``` js
// main.js

require(['jquery'], function($) {
  console.log($);
});
```

And run r.js like so:

``` sh
r.js -o name=main out=main-built.js optimize=none
```

And it produces the following output:

``` js
// ... full text of jQuery source ...

define("jquery", function(){});

require(['jquery'], function($) {
  console.log($);
});

define("main", function(){});
```

Why does it produce the `jquery` and `main` define statements with empty module definitions?

**Note:** turns out this code still works. The value logged to the console is the actual jQuery function, but I'm still curious why these extra statements are generated? If I manually delete them, everything works just fine.

**Comment by jrburke** [comment]
@zllak: I tried the following and did not see a duplicate `define("jquery", ...` in the built file:

```
npm install requirejs
wget http://code.jquery.com/jquery-2.1.3.js -O jquery.js
node_modules/requirejs/bin/r.js -o name=main out=main-built.js optimize=none
```

That is with the main.js as listed in the first post in this ticket being in that directory. I confirmed I was running 2.1.15 of the optimizer by doing:

    node_modules/requirejs/bin/r.js -v

Perhaps if the version of jQuery is different, that could be an issue, and would be good to know, but that latest jQuery 2.1.3 release seems to work correctly.

**Comment by mikkotikkanen** [comment]
I'm running into the same issue in 2.1.16. The issue seems to manifest itself when js optimize is set to `"none"`. When the option is disabled, everything seems to work fine.

**Comment by mikkotikkanen** [comment]
I've now ran into this issue when just moving a file from `/js` (being the root directory for require.js), to `/ext`, so that I have to access it through either `require('../ext/js/script')` or `require('/ext/js/script.js')`, with both of them resulting an empty define to the built code. And this is with minify on as well.

**Comment by mikkotikkanen** [comment]
The file in question starts with `if(!this.xyz) { this.xyz = function(){...`

It seems to end up changed to `this.xyz || (this.xyz = function() {...` with just empy define (`define("../ext/js/script", function() {})`) following it

**Comment by jrburke** [comment]
@mikkotikkanen it sounds like the issue is a bit different than the jquery one, or at least I think it is worth opening a separate issue, hopefully with a pointer to the contents of the file that had the problem, and if it also fails in 2.1.17 it should be mentioned. If you do not want to share the contents of the file publicly, then you can send it to me privately to my jrburke at gmail dot com address, mentioning the requirejs ticket it is related to.

**Comment by mikkotikkanen** [comment]
The issue ended up being configuration related. The shim exports was missing for that script so it ended up creating an empty define.
