### ISSUE TITLE
How to get r.js optimiser to insert define module IDs?

### ISSUE THREAD

**Issue by citizenmatt** [jrburke/r.js#733]
The [readme states](https://github.com/jrburke/r.js#what-makes-it-special) that the optimiser will automatically add module IDs for `define` calls that don't provide one, when concatenating into a single file. However, I can't get this to work. I'm trying to create a single file from several files that use anonymous `define`s, with [`almond`](https://github.com/jrburke/almond), and while it concatenates everything correctly, the anonymous `define`s are not fixed up and replaced with the module ID. Am I doing something wrong?

I'm using the [Emmet project](https://github.com/emmetio/emmet) with the config defined in `[Gruntfile.js](https://github.com/emmetio/emmet/blob/master/Gruntfile.js#L34-L51)`. Or, by using the following (mostly equivalent) `build.js`: 

    ({
        baseUrl: './lib',
        paths: {
            lodash: '../node_modules/lodash/lodash'
        },
        out: './foo.js',
        include: ['./emmet'],
        optimize: 'none'
    })

Am I missing something? Should the `define`s be replaced?

**Comment by jrburke** [comment]
The fix that went in supports using a dist/ version of emmet. The main issue was the UMD wrapper being used started like this:

    !function(e) {

and r.js did not know to break out of the sort of UMD wrapper. It previously just supported function expressions not next to the unary operator. The fix allow for the form above.

**Comment by Giovanni-Mattucci** [comment]
I'm running into this project trying to include projects that are made for webpack where they define the module like this: `define([], factory);`

I am using almond after compile as well. How can I get requireJs to name the define for me on build?

**Comment by jrburke** [comment]
@Giovanni-Mattucci what version of the r.js optimizer are you using? There is a [test for parsing that kind of define](https://github.com/requirejs/r.js/blob/aa349c72576dfb08ee14f599f77c2f8d63ec39e2/build/tests/parse.js#L89), so I expect the latest release, 2.3.2, to at least parse it.

If you are using that version, maybe it is an issue with the optimizer not inserting the module name in that case? If so, then it would be good to have a file to test, so that I can add a similar file to the tests confirm and maintain a fix over time.
