### ISSUE TITLE
Appending ; to last line breaks sourceMappingURL comments

### ISSUE THREAD

**Issue by Rich-Harris** [jrburke/r.js#799]
If the last line of a file is a sourcemap comment...

```js
//# sourceMappingURL=somefile.js.map
```

...r.js adds a semicolon to the URL, breaking everything (see https://github.com/ractivejs/ractive/issues/1874). We'll add a trailing newline at our end as a workaround, but I think this qualifies as a bug in r.js so I thought it worth raising an issue here as well. Thanks

**Comment by jrburke** [comment]
I downloaded http://cdn.ractivejs.org/edge/ractive.js and made sure there was no line return at the end of the file, the sourceMappingURL is the last line, then created a main.js that did `require(['ractive'])`, then ran this command:

    node ~/git/requirejs/r.js/r.js -o name=main out=out.js optimize=none

And it does not place a ; on the sourceMappingURL comment line. This was with r.js master which is just 2.1.16 with some fixes unrelated to this area.

Perhaps an older r.js was being used? Going to close for now since I cannot reproduce. If @tangst has a test case though, feel free to add more info here and we can always reopen later if need be.

**Comment by tangst** [comment]
@jrburke : Thanks for looking at this.  I was using grunt-contrib-requirejs to run r.js.  https://github.com/gruntjs/grunt-contrib-requirejs

I'm no expert developer, but it looks like grunt-contrib-requirejs just uses whatever r.js is installed on the system.  I was using r.js 2.1.15 at the time.

The optimize option was set to uglify.  So, is the problem with uglify that r.js is using?

**Comment by jrburke** [comment]
If uglify was used, then I would not expect the comment to survive that minification, comments are normally stripped.

**Comment by tangst** [comment]
I'm not thinking clearly.  Let me try to recreate this with uglify and no uglify options and see where I saw the error.

**Comment by tangst** [comment]
@jburke: Ok, I ran my Grunt task using optimize = none against ractive 0.6.1 on r.js 2.1.16, and I do get the error. The semicolon is added.  If you say r.js doesn't have this problem, then I can try raising the issue over at the grunt-contrib-requirejs repo.  Perhaps the grunt task is doing something wrong.

**Comment by hjellek** [comment]
Having the same issue, and found the option "skipSemiColonInsertion" after looking around a bit. Turning it off solves the issue (not very surprising), but I really would like to have it turned on as I have had problems previously with libraries not ending correctly. Are there any downsides to just inserting the semicolon with a newline in front of it, except that the file get that much longer when not minified?

@jrburke regarding the sourcemap comment not being stripped by uglify, it does get stripped as long as it does not end with a semicolon. Don't know if that is a bug though.
