### ISSUE TITLE
generateSourceMaps adds second sourceMappingURL entry at end of file

### ISSUE THREAD

**Issue by breuerss** [jrburke/r.js#802]
Compiling a simple Main.js
```javascript
require([
], function () {
    'use strict';
    return {};
});
```
with the following command
`r.js -o Main.js out=out.js name=Main generateSourceMaps=true preserveLicenseComments=false optimize=uglify2`

appends to the file two sourceMappingURL lines:

```javascript
//# sourceMappingURL=out.js
//# sourceMappingURL=out.js.map
```
The first entry causes problems, in at least Safari, reading and using the source map file.
The problem was observed with version 2.1.17.

**Comment by danielchao** [comment]
I see this too. Problem is not present in 2.1.13 (or later, haven't tested).

**Comment by rockResolve** [comment]
I am having a similar problem with generateSourceMaps.  I am optomizing my 'main' module to a single file with an out function.

On RequireJs 2.1.11 I was not getting a sourceMappingURL line added as expected because the out function means the sourceMap is a text parameter and there is no sourceMapping file to get a path from.

But now in 2.1.17 I get an unwanted sourceMappingURL line: //# sourceMappingURL=main-built.js

Because I am optomizing a 'main' module to a single file, uglify guesses the sourceMap file name as 'main-built.js'. But an out function means there is currently no output main-built.js, and the source map file name is missing the .map suffix anyway!

### Cause ###
I traced this in RequireJs version 2.4.16 to the upgraded uglify2 in #709.
(See the double sourceMappingURL in build/tests/lib/sourcemapSingle/main-built.js!)

Uglify2 version 2.4.14 made the change in mishoo/UglifyJS2#468
Uglify2 now always adds the sourceMappingURL line (even if it had to guess the file name)

Noticed here asciidisco/grunt-requirejs#107
And here terinjokes/gulp-uglify#39 with workaround

Double entry seems to come from both Uglify2 & RequireJs adding the lines (since Uglify2 did not previously)

### Fix? ###
To handle callers who dont want a physical file (e.g. node stream processors which may not know the target file names yet),  should Uglify2 have an option to avoid adding the sourceMappingURL line even if a source map is generated?
Or should Uglify2 consumers like RequireJs (and upstream) always expect Uglify2 to add the line?

**Comment by OliverJAsh** [comment]
@rockResolve Did you mean you traced the issue to 2.1.16?

**Comment by OliverJAsh** [comment]
I have the same problem, and it makes my source maps.

**Comment by rockResolve** [comment]
@OliverJAsh Yes I did mean 2.1.16. Updated to avoid others confusion. Thanks.

**Comment by adambiggs** [comment]
I'm still having this issue with v2.1.22 using `gulp-requirejs-optimize` and `gulp-sourcemaps`.
