### ISSUE TITLE
"Mismatched anonymous define() module: undefined" for modules without "factory" function

### ISSUE THREAD

**Issue by ilplotkin** [jrburke/r.js#803]
Upgrading to the latest `r.js` we got `"Mismatched anonymous define() module: undefined"` message.
We reviewed generated file and discovered that all our modules like `define([...]);`
(without "factory" function) were generated without an `ID`.

We use such modules extensively to gather subtrees as single dependence. So far we have to introduce a workaround using `onBuildRead` callback to insert empty "factory" function for such modules.

The issue (seems) was introduced in 2.1.7 version.

**Comment by jrburke** [comment]
It would be helpful to have a more specific example of a file contents that failed to get the name inserted in the define call, as the issue is likely with the placement of the define() in a larger file (like if inside a UMD definition) or the structure of the specific define call. I can then adapt that example to a unit test so I can make sure it does not break again in the future.

**Comment by ilplotkin** [comment]
Please see https://github.com/ilplotkin/r.js-issue-803

**Comment by jrburke** [comment]
The problem are the modules that call define without a factory function:

    define(['./m1']);

In order to avoid false positives of possibly local code in a script that has defined a `define` function for the script's own use, the optimizer wants to only apply name insertion for things that look like calls to an AMD define, so it wants to see a factory function for the module in the signature like so:

    define(['./m1'], function() {});

Doing that change fixes the problem. I apologize if the parser was more lax in previous versions, but these more strict changes were to avoid collisions with define() calls that were not for an AMD module system, where inserting another argument in those could cause breakage.

Going to close as working as designed, but feel free to continue discussion in the ticket.
