### ISSUE TITLE
Can't get "inlineText" to work

### ISSUE THREAD

**Issue by JasperTey** [jrburke/r.js#809]
I can't get the `inlineText: true` functionality to work as expected. Searching past issues, I'm experiencing the same thing as #279, except in my case, `findNestedDependencies: true` is already set, and my `text!` includes are direct define() dependencies.

An example of one of the modules in question:

```
define([
    'knockout',
    'text!./templates/heatmap.html',
    'jquery',
    'underscore',
    'moment',
    'ko/dates',
    'ko/components',
    'mapping'
], function (ko, htmlString, $, _, moment) {
   // Module code ...
});
```

The resulting built module does not end up inlining `text!./templates/heatmap.html`, unless I configure it manually using the `modules` option in my build config.

Out of curiosity, I even tried using the full path to the text template instead of the relative path (./). That didn't make a difference.

I'm stumped. What am I missing here?

**Comment by jrburke** [comment]
That does seem strange. 

What version of the text.js plugin are you using? If it is not a version from requirejs/text, then it could be that type of text.js file does not implement the right methods to cooperate in the build.

If using a requirejs/text plugin, I would make sure that both it and the r.js optimizer is on the latest release. Besides that, I am not sure what the problem could be, and a sample project would help identify the problem.

**Comment by JasperTey** [comment]
I ensured the correct and latest versions of everything you mentioned above, but still no luck. Here's a sample project I created: https://github.com/JasperTey/r.js-sample

I am building on a Windows environment. Might that have something to do with it?

**Comment by jrburke** [comment]
I am sorry for the delay in response. Looks like the issue is the build config does not target any modules for inlining/bundling. If I add this to the build.js, then it does what is expected:

```javascript
    modules: [{
        name: 'modules/heatmap'
    }],
```

The text inlining does not mean it will inline all text plugin resources with modules that reference them, since that could mean to multiple copies across files, and so only applies to module layers targeted by the build, specified by the `modules` section of the build config.

Going to close as a discussion ticket, feel free to continue discussion.

**Comment by JasperTey** [comment]
Ah, okay. So given the following module:

```
define([
    'knockout',
    'text!./templates/heatmap.html',
    'jquery',
    'underscore',
    'moment',
    'ko/dates',
    'mapping'
], function (ko, htmlString, $, _, moment) {
    // Module code ...
});
```

In order to inline only `text!./templates/heatmap.html`, I have to do the following:

```
modules: [{
    name: 'modules/heatmap',
    include: [
        'text!modules/templates/heatmap.html'
    ],
    exclude: [
        'knockout',
        'jquery',
        'underscore',
        'moment',
        'ko/dates',
        'mapping'
    ]
}]
```

Is there a way to do something to the effect of `includeOnly: ['text!modules/templates/heatmap.html']`? Thus eliminating the need to manually list all remaining dependencies in the `exclude` option, which seems tedious when configuring multiple targeted modules where I only want to inline a single dependency.

Side note: using the relative path `text!./templates/heatmap.html` didn't work within the `include` option above and I had to use the full path to the template, which threw me off (is this a bug?).

**Comment by jrburke** [comment]
There is no includeOnly, the idea being that there is likely a top level set of optimized bundles, like the one including knockout, jquery, etc. and that whole bundle can be excluded from a subsequent modules: entry like so:

```javascript
modules: [{
  // This main modules target ends up including base libs
  // like jquery knockout, etc.
  name: 'main'
}, {
  name: 'modules/heatmap',
  // This will exclude all the modules that were traced and
  // and included in the 'main' modules layer.
  exclude: ['main']
}]
```

If you want more fine grained module combining and exclusions, controlled imperatively with your own build code (and therefore the own build code responsible for final file writes), [amodro-trace](https://github.com/amodrojs/amodro-trace) might be a better option.

As to the relative path in modules config, those IDs are top level, absolute IDs, and given that the baseUrl was set to the 'js' directly, IIRC, then asking for './something' at the top level of the ID space will get normalized to 'something' and then to turn that to a path, baseUrl is added to it, so ends up with a 'js/something.js' path. To avoid confusion though absolute IDs are recommended for build config, since it is specified outside of a module and therefore does not have a relative reference.

**Comment by JasperTey** [comment]
Thanks for the clarification. I'm starting to understand how this works now.

I notice when I use the `modules` option along with `inlineText: true`, the text.js plugin file is discarded from the distribution directory during the build. I have other modules that still use text.js, which I haven't targeted in the `modules` option, and they end up breaking due to the missing text.js.

**Comment by JasperTey** [comment]
Nevermind, I figured it out. It was because I had `removeCombined: true`, a setting which I didn't fully understand prior to this.

**Comment by jrburke** [comment]
Also, if using [stubModules](https://github.com/jrburke/r.js/blob/ab4d9000e5a6fc76b3b055b0d9c069b53634122b/build/example.build.js#L316) be sure to remove 'text' from it. Otherwise, that stub definition will be used and will not be useful for dynamically loaded templates.
