### ISSUE TITLE
Is it possible to optimize a config file that has multiple require.config calls?

### ISSUE THREAD

**Issue by mwcz** [jrburke/r.js#814]
For reasons I can get into if desired, my require.config.js file has two calls to `require.config()`.  The first call includes is a hand-curated list of module paths.  The second is a list automatically wired up by bowerRequirejs.  When I run the optimizer, it only recognizes the first require.config call.  Is there a to configure the optimizer to scan for more require.config calls?

Thanks!

**Comment by jrburke** [comment]
It does not right now because there are build cases where the developer explicitly only wants the first one and the second one is used for non-build/runtime purposes. I likely will not provide a declarative option to parse for all the calls in a file, since it does require a decent amount of changes, and it means even more config for people to learn. I would like to expose more primitives though to enable others to build their own custom imperative workflows.

In the meantime, what you might be able to do is before calling the optimizer, use a regexp to extract the second call, save it in a temp file for the build, then as of r.js 2.1.10, mainConfigFile can be an array of file paths, and that temp file can be the second file path in that array.

**Comment by mwcz** [comment]
By unlikely coincidence, that solution is perfect for my use case.  The two `require.config` calls are kept in separate files and concatenated at build time.  Passing an array to mainConfigFile is ideal.

This is why I love RequireJS; for every single issue I've had, a config param already exists that addresses it.  It's just a matter of discovery. :)
