### ISSUE TITLE
OnBuildRead shows files that don't make it into the final file

### ISSUE THREAD

**Issue by ANPabarker** [jrburke/r.js#817]
I can see files being read by r.js in OnBuildRead, but these don't make it into the optimized file. Is there a way to force them to be included? I'm trying to ensure files lazy loaded by couch-potato are included in my build process.

**Comment by jrburke** [comment]
If they are loader plugin resources, then if the loader plugin does not implement the [`write` API](http://requirejs.org/docs/plugins.html#apiwrite), then they will not be included. So the fix is getting the loader plugin to implement a write API.

I am assuming that is the issue, but if not, illustrating more of an example would help identify the problem, and we can reopen as needed.
