### ISSUE TITLE
r.js optimizer and domReady!

### ISSUE THREAD

**Issue by jeroencusters** [jrburke/r.js#818]
I can't run r.js optimizer when my Javascript AMD module contains define(['domReady!']). 
Error message: TypeError: Cannot read property 'normalize' of undefined

When I change this to domReady (without !) then the optimizer has no issues, but this is not the desired solution for our app.

**Comment by gCardinal** [comment]
Could you show me your configuration file? I also had trouble with `domReady!` in my configuration, but I got a different error message, so I'm not sure your problem is the same as mine.

For reference though, domReady started to behave as soon as I added `findNestedDependencies: true` to my configuration. Though, I am using grunt-contrib-requirejs to call r.js, it should be identical if using r.js directly.

**Comment by jeroencusters** [comment]
Hi gCardinal,

Thanks for your reply. This is a part of my configuration file (I have removed the custom libraries):
`require.config({
  baseUrl: '.',
  paths: {
    bootstrap: '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min',
    domReady: '//owncdn/jslib/domReady',
    jquery: '//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min',
  },
  shim: {
    bootstrap: {
      deps: ['jquery']
    }
  }
});`

**Comment by jrburke** [comment]
This can happen if the the source for domReady.js is in a bundle with other modules and that bundle is loaded in the optimizer before the first 'domReady!' dependency is traced. That, or in the build, 'domReady!' path config points to 'empty:' or an empty file.

It works best if the the optimizer can load domReady.js as its own separate module, that is needed for the loader plugin to participate correctly in the build.

Based on the info so far in this bug, I think that is the issue, but if not, perhaps a small example that shows the failure would help, and we can reopen the issue if we trace the failure to a bug.
