### ISSUE TITLE
"main": "require.js"

### ISSUE THREAD

**Issue by monolithed** [jrburke/r.js#854]
Could anyone explain me why the main file is located in `bin/require.js`?

It seems should be like:

```json
{
   "bin": "bin/require.js"
   "main": "require.js"
}
```

Problems:
1. Some modules like `resolve` can not resolve correct path.
2. There're [problems](https://github.com/mailru/jam/blob/master/lib/commands/compile.js#L196) with npm 3 (flat directory structure) in modules like jam

My temporary solution is ugly:

```js
var requirejs = require.resolve('requirejs');
path.join(requirejs, '../../require.js');
```

**Comment by jrburke** [comment]
If this is about the package.json for the npm package 'requirejs':
https://github.com/requirejs/requirejs-npm/blob/master/requirejs/package.json

It is set up that way because requirejs can be used in node, and its optimizer runs in node. That was the primary use case for using requirejs with node and npm. It is only more recently that people have been trying to use npm for front end work.

If you want to use npm to install require.js for use in a front end project, then maybe using the direct URL to the require.js file in the requirejs repo would be a way to go.

Closing as a discussion ticket, feel free to continue discussion here though.
