### ISSUE TITLE
r.js cannot convert define()-calls in a almond-safe way if a function param is an expression

### ISSUE THREAD

**Issue by jrauschenbusch** [jrburke/r.js#874]
Hi all,

While building an application with requireJS and using grunt-requirejs to optimize the app with option almond:true, an error occured while loading the dependency d3.js (v3.5.7): https://github.com/mbostock/d3/issues/2617

It seems that r.js cannot detect function param expressions:

```define(d3)``` will be converted to ```define('d3', d3) // works with almond```

```define(this.d3 = d3)```  will not be converted. Therefore the output is still ```define(this.d3 = d3) // fails with almond```

**Comment by jrburke** [comment]
The name insertion works by static analysis of the file. In order to prevent falsely identifying some other define as an AMD define, only certain patterns are used to detect the define call. 

Allowing arbitrary expressions makes this harder and more likely a false positive is made. Arbitrary expressions make it hard to determine if the result of the expression is something that should match the data types expected in an AMD define call.

It is best if there is consistency in how the UMD detection blocks are done for this reason, and one of the reasons the umdjs/umd patterns exist, is to create some common conventions that can be effectively targeted by tools.

I appreciate that this was addressed in d3 already, and I would prefer to address it that way given the above constraints. So closing, but feel free to continue discussion here.
