### ISSUE TITLE
I am getting an error of "modulesWithNames  is not defined" on write-bundles branch  

### ISSUE THREAD

**Issue by deepprimod** [jrburke/r.js#876]
Working on making bundles as given in 
https://github.com/jrburke/r.js/issues/613

I tried to run the sample code in this directory and I am getting this error, Also my bundle file is not getting created
```
Tracing dependencies for: rollup
Error: ReferenceError: modulesWithNames is not defined
    at C:\Users\deep.singh\AppData\Roaming\npm\node_modules\requirejs\bin\r.js:2
8974:31
```

**Comment by jrburke** [comment]
The branch mentioned in #613 is definitely not complete. [This comment](https://github.com/jrburke/r.js/issues/613#issuecomment-157560647) mentions a commit that also mentions the harder issue to resolve to get it to work, so I do not consider that branch usable at this time.

Going to close this ticket since it is on a not-complete branch, but feel free to continue discussion here.

**Comment by deepprimod** [comment]
I there any way that I can make bundles in an automated way for now?
