### ISSUE TITLE
r.js v2.1.22 problem

### ISSUE THREAD

**Issue by zmrdlb** [jrburke/r.js#879]
requirejs 2.1.22 and r.js 2.1.22 can read reqiurejs.config:
paths: {
      ...
}

but r.js 2.1.22 can not read this:
paths: {
      'layer': 'module/ui/layer'
}
layer/msgConfirm，path should be module/ui/layer/msgConfirm，but in fact，path is layer/msgConfirm。wrong

**Comment by jrburke** [comment]
A more fleshed out example might help, but r.js 2.1.22 can read paths config, otherwise some of the unit tests would fail. 

My guess is perhaps a secondary requirejs.config() call with that paths config is in play, maybe nested in another module? Not sure though, more detail or maybe a small test case is needed to figure out if perhaps r.js cannot find the requirejs.config call, I'm assuming maybe mainConfigFile config might be in use?

Closing for now, but feel free to continue discussion and we can reopen if we can identify the root of the issue.
