### ISSUE TITLE
r.js with Rhino 1.7 Release 4

### ISSUE THREAD

**Issue by gfinocchiaro** [jrburke/r.js#888]
Trying to launch r.js with Rhino version 1.7 release 4 (2012 06 19), I get the following error:

```sh
js: "r.js", line 1: Encountered code generation error while compiling script: generated bytecode for method exceeds 64K limit.
```

Any idea?

Thanks
Gianluca

**Comment by jrburke** [comment]
Looks like the optimization level needs to be set to -1 for it to work in Rhino now, which can be done on the command line via `-opt -1`. That slows down the execution though. If you can use Nashorn instead of rhino, that is likely a better story going forward.

**Comment by pinnamreddy** [comment]
I am trying to optimize my script using Nashorn instead of rhino, I am ran through gradle build. I am following like below.
ant.java(classname:'jdk.nashorn.tools.jjs.Main', classpath: configurations.rjs.asPath, output: logFile.toString(), fork: true, failonerror: true, dir: runDir.toString()) {
arg(value: rjsFile.toString())
arg(value: '-o')
arg(value: buildConfigFile.toString()) }
**Below is my class path:**
JAVA_HOME=/usr/lib/jvm/java-8-oracle
PATH=$PATH:$JAVA_HOME/bin/jjs
I am  getting error like below.
Execution failed for task ':web:test:rjs'.
> Java returned: 1
and build.log file I found below error.
**Error: Could not find or load main class jdk.nashorn.tools.jjs.Main**

Any Idea?

**Comment by jrburke** [comment]
I don't know enough about gradle to know how to configure it to find the class mentioned.

**Comment by pinnamreddy** [comment]
any idea to script optimize using Nashorn?

Thanks

**Comment by jrburke** [comment]
This is what I have figured out for the unit tests:
https://github.com/requirejs/r.js/blob/master/build/tests/alljnashorn.sh

For running a build.js through the optimizer, I think it would look like:

```
jjs -cp path/to/compiler.jar -scripting ../../r.js -- -o build.js
```
